import { Component } from "solid-js";

const PromptHistorySection: Component = () => {
	const promptHistory = [
		{
			step: "1. Planning",
			title: "Initial Understanding & Documentation",
			prompt:
				"For a university exam, I was assigned this project: B07 - AI-Assisted WebAssembly Binary Decoder and Text (WAT) Generator. I would like you to explain to me, first of all, what it is and what are the main topics I need to know. Then, I want us to make a document to define all the steps of the implementation of the project. Let's create a well-detailed functional and technical document.",
			observation:
				"This initial step provided a comprehensive breakdown of the assignment, explaining the WebAssembly binary format and the structure of WAT. The AI successfully generated a functional and technical specification document that served as the roadmap for the entire development process.",
		},
		{
			step: "2. Design",
			title: "Stack Definition & UI",
			prompt:
				"I want to work with the SolidJS framework in TypeScript. The interface must be able to load a binary file. After processing, it should show the resulting WAT view. Please use Google's Material Design 3 style. Make it so it is easier to read.",
			observation:
				"SolidJS was chosen for its fine-grained reactivity. Google's Material Design 3 provided a modern, clean, and accessible look. The AI helped integrate the components seamlessly into the SolidJS app.",
		},
		{
			step: "3. Implementation",
			title: "Environment Setup",
			prompt:
				"I have created a GitHub repository. I cloned it to my machine, opened the folder, and added the functional_spec.md file we generated. Let's start the implementation based on the specs (remembering the Material Design 3 style). Ignore the README for now.",
			observation:
				"The setup process was smooth. Providing the context that the repository was already active allowed the AI to jump straight into generating the core files and the project structure.",
		},
		{
			step: "4. Verification",
			title: "Unit Testing & QA",
			prompt: "Build also some small WASM tools to verify the decoder?",
			observation:
				"The AI generated several WASM binaries to test the decoder. This was essential for verifying that the binary-to-text conversion logic was handling different opcodes correctly. The results were compared with wasm2wat for quality assurance.",
		},
		{
			step: "5. Debugging",
			title: "Adding Missing Instructions",
			prompt:
				"Using the application i passed the @factorial.wasm file generated by the generate_wasm.mjs. It seems that some code are not recognized. It's missing something?",
			observation:
				"The decoder was missing definitions for several 64-bit integer (i64) operations used in the factorial test file (0x51: i64.eqz, 0x7d: i64.sub, 0x7e: i64.mul). The AI identified and provided the correct mapping.",
		},
		{
			step: "6. Refinement",
			title: "Fix Opcode Mapping",
			prompt:
				"The opcode mapping is still not 100% correct. Can you double check the WebAssembly specification and provide the complete list of opcodes for core instructions?",
			observation:
				"The AI provided a more comprehensive list of opcodes by referencing the official WASM specification. This manual cross-referencing allowed the final tool to be much more robust.",
		},
	];

	return (
		<section class="space-y-6">
			<div class="flex items-center justify-between border-b pb-4 border-outline/10">
				<h2 class="text-3xl font-bold text-primary">Prompt History</h2>
				<span class="px-3 py-1 bg-secondary/10 text-secondary text-xs font-bold rounded-full uppercase tracking-wider">
					AI-Assisted Development
				</span>
			</div>
			<p class="text-onSurface/70 italic text-lg leading-relaxed">
				This log tracks the interaction with AI that led to the creation of the Wasm Decoder, documenting the
				prompts used and the resulting development reflections.
			</p>

			<div class="space-y-10 mt-8">
				{promptHistory.map((item, i) => (
					<div class="relative pl-8 border-l-2 border-primary/20 hover:border-primary/50 transition-colors pb-2">
						<div class="absolute -left-[9px] top-0 w-4 h-4 rounded-full bg-primary border-4 border-background shadow-sm"></div>
						<div class="mb-2">
							<span class="text-xs font-bold text-outline uppercase tracking-widest">{item.step}</span>
							<h3 class="text-xl font-bold text-primary leading-tight mt-1">{item.title}</h3>
						</div>

						<div class="mt-4 p-6 bg-primary/5 rounded-2xl border border-primary/10">
							<div class="flex items-center gap-2 mb-3">
								<span class="text-primary text-sm font-bold flex items-center gap-1">
									<span class="w-2 h-2 rounded-full bg-primary"></span>
									AI PROMPT
								</span>
							</div>
							<p class="text-sm font-mono text-onSurface/90 leading-relaxed italic">"{item.prompt}"</p>
						</div>

						<div class="mt-4 p-5 bg-secondary/5 rounded-2xl border border-secondary/10 relative overflow-hidden">
							<div class="absolute top-0 right-0 p-2 text-secondary/20">
								<svg class="w-12 h-12" fill="currentColor" viewBox="0 0 24 24">
									<path d="M12 2C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm1 15h-2v-6h2v6zm0-8h-2V7h2v2z" />
								</svg>
							</div>
							<div class="flex items-center gap-2 mb-2">
								<span class="text-secondary text-xs font-bold uppercase tracking-wider">
									Reflection & Observations
								</span>
							</div>
							<p class="text-sm text-onSurface/80 leading-relaxed relative z-10">{item.observation}</p>
						</div>
					</div>
				))}
			</div>
		</section>
	);
};

export default PromptHistorySection;
